server:
  port: 8081
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/books/**